name: OpenTofu OCI Provisioning

on:
  pull_request:
    branches: [ main ]
    paths: [ "challenge3/**" ]
  push:
    branches: [ main ]
    paths: [ "challenge3/**" ]

jobs:
  opentofu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: challenge3
    env:
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
      TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
      TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: Tofu Init
        run: tofu init

      - name: Tofu Validate
        run: tofu validate

      - name: Tofu Plan
        run: tofu plan -out=tfplan

      - name: Tofu Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve tfplan
